# Question 1

## (i)
The primal problem is:
$$\underset{\pi\geq0}{\max}\sum_{x,y}\pi_{xy}\Phi_{xy}$$
s.t.
$$\sum_{x}\pi_{xy} \leq 1 \quad \forall y \in \{1, 2, 3, 4\}$$
$$\sum_{y}\pi_{xy} \leq 1 \quad \forall x \in \{1, 2, 3\}$$

In [1]:
using Gurobi, JuMP

In [37]:
Φ = [1 3 2 3; 2 5 4 1; 2 1 2 0]

m = Model(solver=GurobiSolver(Presolve=0, OutputFlag=0))

@variable(m, π[1:3, 1:4] >= 0)
@constraint(m, marginal_y[y=1:4], sum(π[x, y] for x in 1:3) <= 1)
@constraint(m, marginal_x[x=1:3], sum(π[x, y] for y in 1:4) <= 1)
@objective(m, Max, sum(sum(π[x, y] * Φ[x, y] for x in 1:3) for y in 1:4))

solve(m)

:Optimal

Academic license - for non-commercial use only


## (ii)

In [28]:
getvalue(π)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0

## (iii)

In [35]:
getdual(marginal_x)

3-element Array{Float64,1}:
 3.0
 5.0
 2.0

In [34]:
getdual(marginal_y)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

Intuitively, man 1 could threaten woman 4 to leave her for woman 2 (whom he needs to offer 0). Woman 2 cannot threaten man 2, because if she went to man 1, she would need to offer him 3 (leaves 0 for her), and man 3 would not want to match with her, again, she has no bargaining power. Man 3 can freely choose between woman 1 and 3 and extract the whole surplus.

## (iv)
$W$ increases by $\epsilon$ and the surplus goes to man 2.

## (v)
Nothing changes.

# Question 2
## (i)
Since $\Phi$ is twice continuously differentialbe, supermodularity is equivalent to $\frac{\partial^2 \Phi(x,y)}{\partial x \partial y \geq 0}$. For the $\Phi$ at hand:
$$\frac{\partial^2 \Phi(x,y)}{\partial x \partial y} = \kappa y^{\kappa -1} \geq 0$$
We can expect positive assortative matching.

## (ii)

Since $F_X(x) = 1-\big(1-\frac{\beta x}{B}\big)^\frac{1}{\beta}$, and the fact that the rank of $x$ and the rank of the matched $y$ agrees (because of the rearrangement theorem):

$$T(x) = y = A \big(1-\frac{\beta x}{B}\big)^{-\frac{\alpha}{\beta}}$$

## (iii)
The constraints of the dual problem are equivalent to:
$$v(y) = \underset{x}{\max} \{\Phi(x,y) - w(x) \}$$
which implies the necessary first order condition:
$$\frac{\partial \Phi}{\partial x}(x,y) = 1y^\kappa = A \Big(1-\frac{\beta x}{B}\Big)^{-\frac{\kappa \alpha}{\beta}} = w'(x)$$
$$\frac{A\big(\beta x - B\big) \Big(1-\frac{\beta x}{B}\Big)^{-\frac{\kappa \alpha}{\beta}}}{\beta - \kappa \alpha}$$

# Question 3
## (i)

The primal problem is:
$$\underset{\pi\geq0}{\max}\sum_{x,y}\mu_{xy}\Phi_{xy}$$
s.t.
$$\sum_{x}\mu_{xy} \leq m_y \quad \forall y$$
$$\sum_{y}\mu_{xy} \leq n_x \quad \forall x$$
The dual is:
$$\underset{u, v \geq 0}{\min}\sum_{x}n_x u_x + \sum_{y}m_y v_y$$
s.t.
$$u_x + v_y \geq \Phi_{xy} \quad \forall x,y$$

Let me write out clear definitions. A payoff vector $(u, v) \in \mathbb{R}^{N+M}$ is stable, if $\exists \mu{M}$ such that $(\mu, u, v)$ is what slide 14 of block 4 calls a "stable matching", which is used synonymously with "stable outcome". (Mind: the conditions on $\mu$ are already part of the definition on the slides).

Now, feasibility means exactly $u_x + v_y \geq \Phi_{xy} \quad \forall x,y$.

If $(u,v,)$ is an optimal solution to the dual, then it is stable.


## (ii)

Let $S$ be a set containing all stable payoff vectors and $\underline{u}_x$ is the minimal surplus $x$ can achieve in all stable payoffs. (Mind: we assume the minimum exists, i.e. that the projection on the $x$-th coordinate of the $u$ vectors is a closed set). Similarly, $\bar{v}_y$ is the maximal value $y$ can achieve.

To show that $(\underline{u}_x, \bar{v}_y) \in \mathbb{R}^{N+M}$ is a stable payoff, I need to find a $\mu$ and check conditions  (5), (6), and (7) on the slides.

Let $\mu$ be one that is associated with a $(u,v)$ that minimizes or maximizes the optimization for $x$ or $y$, any one of those will do.

* (5): fulfilled by definition
* (6): Choose any $x$, then by definition $\underline{u}_x + v_y^x \geq \Phi_{xy}$, where $v_y^x$ are the women's payoffs in the payoff vector that minimizes $x$'s payoff. But $v_y^x \leq \bar{v}_y$, hence also $\underline{u}_x + \bar{v}_y \geq \Phi_{xy} \, \forall y$. An analogous argument holds for $y$.
* (7): Suppose contrarily that $x$ and $y$ are matched, but $\underline{u}_x + \bar{v}_y > \Phi_{xy}$. Then $\underline{u}_x$ was not minimal. Contracition.

## (iii)
First, solve the primal problem, this yields $(W, \mu, u, v)$.
Then, solve:

$$\underset{u, v \geq 0}{\min}\sum_{x}u_x - \sum_{y}v_y$$
$$u_x + v_y \geq \Phi_{xy} \quad \forall x,y \,\text{such that} \, \mu_{xy}=0$$
$$u_x + v_y = \Phi_{xy} \quad \forall x,y \,\text{such that} \, \mu_{xy}>0$$
$$\sum_{x}n_x u_x + \sum_{y}m_y v_y = W$$

## (iv)

In [ ]:
m = Model(solver=GurobiSolver(Presolve=0, OutputFlag=0))

@variable(m, u[1:nx] >= 0)
@variable(m, v[1:ny] >= 0)

for i in 1:nx, j in 1:ny
    if getvalue(\pi)[i,j] > 0
        @constraint(m, u[i] + u[j] == Φ{i, j})
    else
        @constraint(m, u[i] + u[j] >= Φ{i, j})
    end
end

@constraint(m, sum(nx[x] * u[x] for x in 1:nx) + sum(ny[y] * v[y] for y in 1:ny) == W)

@objective(m, Min, sum(u[x] for x in 1:nx) - sum(v[y] for y in 1:ny))

solve(m)

# Question 7

In [24]:
using Distributions
nbDraws = 1000
ϵ_iy = rand(MvNormal(zeros(6), 0.5 * eye(6) + 0.5 * ones(6,6)), nbDraws)'
s_y = [0.216191, 0.263915, 0.141353, 0.176405, 0.113032, 0.089103]
s_y = s_y .+ (1-sum(s_y))/6 #it needs to sum to one!

m = Model(solver=GurobiSolver(Presolve=0, OutputFlag=0))

@variable(m, π[1:nbDraws, 1:6] >= 0)
@constraint(m, marginal_y[y=1:6], sum(π[x, y] for x in 1:nbDraws) == s_y[y])
@constraint(m, marginal_x[x=1:nbDraws], sum(π[x, y] for y in 1:6) == 1/nbDraws)
@objective(m, Max, sum(sum(π[x, y] * ϵ_iy[x, y] for x in 1:nbDraws) for y in 1:6))

solve(m)

Uhat_y = - getdual(marginal_y) + getdual(marginal_y)[end]

6-element Array{Float64,1}:
 0.541909
 0.547225
 0.287581
 0.39739 
 0.151758
 0.0     

Academic license - for non-commercial use only


# Question 8
## (a)
Let $\mathcal{A}$ be the set of edges, and $X$ be the set of nodes. $\nabla \in \mathbb{R}^{|\mathcal{A}| \times |X|}$.
The dual is:
$$\underset{\phi}{\max}\sum_{x \in X}n_x \phi_x - \sigma \sum_{a \in A} \exp \Big(\frac{\sum_x \nabla_{ax} \phi_x - c_{a} - \sigma}{\sigma}\Big)$$
This is an unconstrained optimization problem with first order conditions:
$$\forall x\quad n_x = \sum_a \nabla_{ax} \exp\Big(\frac{\sum_{x'} \nabla_{ax'} \phi_{x'} - c_a - \sigma}{\sigma}\Big)$$

## (b)
The easiest would be to type up the problem and solve it with IpOpt or Knitro, or we do IPFP.

## (c)
The non-linear program is easy:

In [ ]:
using Ipopt
m = Model(solver=IpoptSolver()

@variable(m, ϕ[1:nx])

@NLobjective(m, Max, sum(nx[x] * ϕ[x] for x in 1:nx) - σ * sum(exp((sum(∇[a,x] * ϕ[x] for x in 1:nx) -c[a] -σ)/σ) for a in 1:na))

solve(m)

The IFPF needs some more work:
$$\forall x\quad n_x = \sum_a \nabla_{ax} \cdot \exp\Big(\frac{\nabla_{ax} \phi_{x}}{\sigma}\Big) \cdot \exp\Big(\frac{\sum_{x'\neq x} \nabla_{ax'} \phi_{x'} - c_a - \sigma}{\sigma}\Big)$$
But I know how $\nabla$ looks like!

$$\forall x\quad n_x = \exp\Big(\frac{\phi_{x}}{\sigma}\Big) \cdot \sum_{a: \, \text{inflow to x}}  \exp\Big(\frac{\sum_{x'\neq x} \nabla_{ax'} \phi_{x'} - c_a - \sigma}{\sigma}\Big) - 
\exp\Big(\frac{-\phi_{x}}{\sigma}\Big) \cdot \sum_{a: \, \text{outflow from x}}  \exp\Big(\frac{\sum_{x'\neq x} \nabla_{ax'} \phi_{x'} - c_a - \sigma}{\sigma}\Big)$$

It does not seem like $\phi$ could be explicitly expressed from $\phi_{x'}$, so I would need to use a root finding method to find $\phi_x$. I could probably work out bounds on $\phi_x$ and solve the equation with bisection, but I am running out of time.

Here is pseudo-code:

In [ ]:
function ipfp(∇, c; σ = 1e-1, tol=1e-6)
    ϕ = zeros(size(∇, 1))
    ϕold = copy(ϕ)

    while (error > tol)

        for i in 1:length(ϕ)
            #solve for ϕ[i] as a function of ϕold[-i] using bisection
        end
        
        error = maximum(abs.(ϕ - ϕold))
        ϕold = copy(ϕ)
    end

    return ϕ
end